version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: premium_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: t462825*
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: